import jsPDF from 'jspdf';
import { Scores } from './scoreCalculations';
import { Personality } from './personalityAlgorithm';

interface GameChoice {
  scenarioId: number;
  scenarioTitle: string;
  choiceSelected: string;
  choiceText: string;
  impacts: {
    integrity: number;
    trust: number;
    sustainability: number;
  };
}

interface ReflectionAnswers {
  [key: string]: string;
}

interface PDFData {
  sessionId: string;
  completedAt: string;
  personality: Personality;
  finalScores: Scores;
  choices: GameChoice[];
  reflections?: ReflectionAnswers;
}

const REFLECTION_QUESTIONS = [
  'Which dilemma made you think twice?',
  'Did you prioritize quick results or honesty?',
  'When did your integrity drop the most?',
  'What is "small corruption" in daily life?',
  'How will you maintain honesty moving forward?',
];

export function generateReflectionPDF(data: PDFData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;

  // Page 1: Results Summary
  doc.setFontSize(24);
  doc.setTextColor(0, 255, 159); // Neon green
  doc.text('Deci$ion: The Integrity Game', margin, 25);

  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text('YOUR MORAL PROFILE', margin, 40);

  doc.setFontSize(11);
  doc.text(`Date: ${data.completedAt}`, margin, 50);
  doc.text(`Session ID: ${data.sessionId.substring(0, 8)}...`, margin, 57);

  // Personality Type
  doc.setFontSize(20);
  doc.setTextColor(0, 255, 159);
  doc.text(`YOU ARE: ${data.personality.title.toUpperCase()} ${data.personality.icon}`, margin, 75);

  // Description
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  const descLines = doc.splitTextToSize(data.personality.description, maxWidth);
  doc.text(descLines, margin, 88);

  // Reflection
  const reflectionLines = doc.splitTextToSize(data.personality.reflection, maxWidth);
  doc.text(reflectionLines, margin, 88 + descLines.length * 6);

  // Scores
  const scoresY = 88 + descLines.length * 6 + reflectionLines.length * 6 + 10;
  doc.setFontSize(14);
  doc.setTextColor(0, 255, 159);
  doc.text('YOUR FINAL SCORES:', margin, scoresY);

  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`💎 Integrity:        ${data.finalScores.integrity}%`, margin, scoresY + 12);
  doc.text(`🤝 Trust:            ${data.finalScores.trust}%`, margin, scoresY + 22);
  doc.text(`🌱 Sustainability:   ${data.finalScores.sustainability}%`, margin, scoresY + 32);

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by Deci$ion Game | Supporting SDG 4 & SDG 16', margin, 280);

  // Page 2: Reflections (if provided)
  if (data.reflections && Object.keys(data.reflections).length > 0) {
    doc.addPage();
    doc.setFontSize(16);
    doc.setTextColor(0, 255, 159);
    doc.text('PERSONAL REFLECTIONS', margin, 25);

    let yPos = 40;
    for (let i = 1; i <= 5; i++) {
      const answer = data.reflections[`question${i}`];
      if (answer && answer.trim()) {
        doc.setFontSize(11);
        doc.setTextColor(0, 0, 0);
        doc.setFont(undefined, 'bold');
        doc.text(`${i}. ${REFLECTION_QUESTIONS[i - 1]}`, margin, yPos);

        doc.setFont(undefined, 'normal');
        doc.setFontSize(10);
        const answerLines = doc.splitTextToSize(answer, maxWidth);
        doc.text(answerLines, margin, yPos + 7);

        yPos += 7 + answerLines.length * 5 + 8;

        // Add new page if running out of space
        if (yPos > 270) {
          doc.addPage();
          yPos = 25;
        }
      }
    }
  }

  // Page 3: Choice Summary
  doc.addPage();
  doc.setFontSize(16);
  doc.setTextColor(0, 255, 159);
  doc.text('YOUR DECISION JOURNEY', margin, 25);

  let yPos = 40;
  data.choices.forEach((choice, index) => {
    // Add new page if needed
    if (yPos > 250) {
      doc.addPage();
      yPos = 25;
    }

    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.setFont(undefined, 'bold');
    doc.text(`SCENARIO ${index + 1}: ${choice.scenarioTitle}`, margin, yPos);

    doc.setFont(undefined, 'normal');
    doc.setFontSize(9);
    const choiceTextLines = doc.splitTextToSize(`Choice ${choice.choiceSelected}: ${choice.choiceText}`, maxWidth);
    doc.text(choiceTextLines, margin, yPos + 6);

    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    const impactText = `Impact: ${choice.impacts.integrity >= 0 ? '+' : ''}${choice.impacts.integrity} Integrity, ${choice.impacts.trust >= 0 ? '+' : ''}${choice.impacts.trust} Trust, ${choice.impacts.sustainability >= 0 ? '+' : ''}${choice.impacts.sustainability} Sustainability`;
    doc.text(impactText, margin, yPos + 6 + choiceTextLines.length * 4 + 3);

    yPos += 6 + choiceTextLines.length * 4 + 8 + 8;
  });

  // Save the PDF
  doc.save(`decision-game-results-${data.sessionId.substring(0, 8)}.pdf`);
}
